version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: simplecrm-app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - web

  nginx:
    image: nginx:stable-alpine
    container_name: simplecrm-nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - web

  mysql:
    image: mysql:8.0
    container_name: simplecrm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - web

volumes:
  mysql_data:

networks:
  web:
    name: web
